# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:

- stage: Veracode

  jobs:
  - job: Build

    steps:

    - task: Bash@3
      displayName: Veracode Container Security - Scan
      inputs:
        targetType: 'inline'
        script: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          export VERACODE_API_KEY_ID=$(VID)
          export VERACODE_API_KEY_SECRET=$(VKEY)
          ./veracode scan --type repo --source https://github.com/bridgecrewio/terragoat -o terragoat.json

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'terragoat.json'
        ArtifactName: 'terragoat.json'
        publishLocation: 'Container'

    - task: Bash@3
      displayName: 'Veracode Container Security - Policy Check'
      inputs:
        targetType: 'inline'
        script: |
          PASS=$(jq -r '."policy-passed"' terragoat.json)
          echo "Passed policy: $PASS"
          if $PASS; then
            exit 0
          else
            exit 1
          fi