# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:

- stage: Veracode

  jobs:
  - job: Build

    steps:

    - task: Bash@3
      displayName: Veracode Container Security
      inputs:
        targetType: 'inline'
        script: |
          curl -fsS https://tools.veracode.com/veracode-cli/install | sh
          export VERACODE_API_KEY_ID=$(VID)
          export VERACODE_API_KEY_SECRET=$(VKEY)
          ./veracode scan --type repo --source https://github.com/bridgecrewio/terragoat -o terragoat.json
          ls -al
          cat terragoat.json
