# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script:
    echo "[INFO - Running Veracode Container Security...]"
  displayName: 'Veracode Container Security'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      export VERACODE_API_KEY_ID=$(vid)
      export VERACODE_API_KEY_SECRET=$(vkey)
      ./veracode scan --type image --source juliantotzek/verademo:latest -o Verademo.json
      ls -al
