# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script:
    echo "[INFO - Installing Docker CLI...]"
  displayName: 'Docker CLI Install'
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: |
    echo "[INFO - Pulling Docker Image...]"
    docker pull centos:7
  displayName: 'Pull Docker Image'

- task: CmdLine@2
  displayName: SCA - Container Scan
  inputs:
    script: |
      export SRCCLR_PROJECT_NAME=CentOS7
      export SRCCLR_API_TOKEN="$(SRCCLR_API_TOKEN)"
      export SRCCLR_WORKSPACE_SLUG=900tQpQ
      curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --image centos:7

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      export VERACODE_API_KEY_ID=$(vid)
      export VERACODE_API_KEY_SECRET=$(vkey)
      ./veracode scan --type image --source juliantotzek/verademo:latest -o Verademo.json
      ls -al
